
CFLAGS = -O2 -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Werror=implicit-function-declaration -Werror=missing-prototypes

dtid : dtid.c
	-rm dtid
	cc -o dtid dtid.c

all: dtid

.PHONY : all
clean :
	-rm dtid
